dataset: cifar100

eval_every_x_epochs: 5

model: joint
convnet: resnet18
convnet_config:
  nf: 64

lr: 0.1
weight_decay: 0
scheduling:
  - 50
  - 100
  - 125
lr_decay: 0.1
optimizer: sgd
epochs: 150
