dataset: cifar100

eval_every_x_epochs: 5

model: joint
convnet: resnet18
convnet_config:
  nf: 64

lr: 0.1
weight_decay: 0.0005
scheduling:
  - 60
  - 120
  - 160
lr_decay: 0.2
optimizer: sgd
epochs: 200
