dataset: cifar100
validation: 0.1
eval_every_x_epochs: 5

model: joint
convnet: resnet18
convnet_config:
  nf: 64

lr: 0.3
weight_decay: 0
scheduling:
  - 150
  - 300
lr_decay: 0.1
optimizer: sgd
epochs: 400
