dataset:
  type: tinyimg
  root: /home/zhiyuan/CIL-CN/datasets/
  batch_size: 32
model:
  type: multi
  multi_setting: cls
  backbone: ResNet18
  header_mode: big
  buffer:
  selector:
  pretrained: ImageNet
  pretrain_model: /home/zhiyuan/CIL-CN/saved_models/model_best.pth.tar
optim:
  type: SGD
  lr: 0.01
  weight_decay: 0.0002
  epochs: 150
  drop:
    type: point
    val:
      - 50
      - 100
      - 125
ckpt:
logger:
  root: /home/zhiyuan/CIL-CN/log/
  name: multi_lr0.01_wd2e-4_cls
params: