dataset:
  type: cifar10
  root: /Users/binah/projects/CIL-CN/datasets
  batch_size: 32
model:
  type: sgd
  backbone: ResNet18
  buffer:
  selector:
optim:
  type: SGD
  lr: 0.1
  epochs: 1
  drop:
ckpt:
logger:
params: