dataset: cifar100

model: der
convnet: multinet
convnet_config:
  pretrained_model: /home/zhiyuan/CIL-CN/saved_models/der_imagenet_official.pth
  #prefix: "convnet.convnets.0."
  sub_convnet: resnet18
  sub_convnet_config:
    last_relu: True
    nf: 64
    initial_kernel: 7

fixed_memory: False
memory_size: 10000

eval_type: cnn

classifier_config:
  type: auxcls
  normalize: False
  use_bias: False
  reuse_oldfc: False
  aux_n+1: True

task_max: 10

eval_every_x_epochs: 10

distillation: "none"
temperature: 1
dynamic_weight_decay: False
extract_no_act: False

finetuning_config:
  sampling: decouple
  tuning: classifier
  lr: 0.05
  epochs: 80
  weight_decay: 0.000
  temperature: 5.0
  scheduling: cosine
  lr_decay: 0.1
  scaling: null

# Scheduling
scheduling: cosine
warmup:
  total_epoch: 10
  multiplier: 1
  only_first_step: False

# Misc
epochs: 100
lr: 0.1
lr_decay: 0.1
optimizer: sgd
proxy_per_class: 1
weight_decay: 0.000

dataset_transforms:
  color_jitter: true
