dataset: cifar100

model: der
convnet: multinet
convnet_config:
  #pretrained_model: /home/zhiyuan/CIL-CN/saved_models/der_imagenet_official.pth
  #prefix: "convnet.convnets.0."
  sub_convnet: resnet18
  sub_convnet_config:
    last_relu: True
    nf: 64
    #initial_kernel: 7
  with_super_split: False
  use_soft_mask: True
  max_super_split: 4
  use_oracle_super_label: False
  reuse_old: True

lambda_s: 0.75

fixed_memory: False
memory_size: 2000

eval_type: cnn

classifier_config:
  type: auxcls
  normalize: False
  use_bias: False
  reuse_oldfc: False
  aux_n+1: True

task_max: 10

eval_every_x_epochs: 10

distillation: "none"
temperature: 1
dynamic_weight_decay: False
extract_no_act: False

finetuning_config:
  sampling: decouple
  tuning: classifier
  lr: 0.05
  epochs: 50
  weight_decay: 0.0001
  temperature: 5.0
  scheduling:
    - 15
    - 30
  scaling: null

# Scheduling
scheduling:
  - 40
  - 60
  - 80
warmup:
  total_epoch: 10
  multiplier: 1
  only_first_step: False

# Misc
epochs: 90
lr: 0.1
optimizer: sgd
proxy_per_class: 1
weight_decay: 0.0001

dataset_transforms:
  color_jitter: true
